app:
  cookie:
    same-site: Lax
    secure: false

  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration: 60
    refresh-token-expiration: 604800

spring:
  application:
    name: auth-backend
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080



logging:
  level:
    com.example.auth: DEBUG
    org.springframework.web: DEBUG

# เพิ่ม CORS configuration
cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true


#  Environment	secure	sameSite
#  Localhost (HTTP)	false	Lax
#  HTTPS (same domain)	true	Strict
#  HTTPS (cross domain)	true	None